Repository Vikash-8090-Yadav/Future.WebNet, pull requests merged in 2022-09, with the labels that each got.

#47 Adding readme.md file in level 0 and correct all the grammatical errors
  Level0/SendToEather/Truf/test/.gitkeep
  Level0/SendToEther/README.MD
  Level0/SendToEther/Truf/build/contracts/Migrations.json
  Level0/SendToEther/Truf/build/contracts/sendeather.json
  Level0/SendToEther/Truf/contracts/Migrations.sol
  Level0/SendToEther/Truf/contracts/sendether.sol
  Level0/SendToEther/Truf/migrations/1_initial_migration.js
  Level0/SendToEther/Truf/migrations/2_initial_migration.js
  Level0/SendToEther/Truf/test/.gitkeep
  Level0/SendToEther/Truf/truffle-config.js
  Level0/SendToEther/index.css
  Level0/SendToEther/index.html
  Level0/SendToEther/index.js
  Level0/readme.md
Labels: SSOC22, SSOC22-BEGINNER

#48 Added more projects
  Project_Ideas/README.md
Labels: SSOC22, SSOC22-INTERMEDIATE

#49 How to Start Blockchain
  Blog/README.md
Labels: SSOC22, SSOC22-INTERMEDIATE

#52 Creating the contributing.md for this repo
  CONTRIBUTING.md
Labels: SSOC22, SSOC22-INTERMEDIATE

#58 added all the files for the staking dapp
  Level1/staking-dapp/.gitignore
  Level1/staking-dapp/README.md
  Level1/staking-dapp/smart-contract/README.md
  Level1/staking-dapp/smart-contract/cache/solidity-files-cache.json
  Level1/staking-dapp/smart-contract/contracts/Staking.sol
  Level1/staking-dapp/smart-contract/hardhat.config.js
  Level1/staking-dapp/smart-contract/package-lock.json
  Level1/staking-dapp/smart-contract/package.json
  Level1/staking-dapp/smart-contract/scripts/deploy.js
  Level1/staking-dapp/smart-contract/test/Lock.js
  Level1/staking-dapp/stakify/README.md
  Level1/staking-dapp/stakify/package-lock.json
  Level1/staking-dapp/stakify/package.json
  Level1/staking-dapp/stakify/public/favicon.ico
  Level1/staking-dapp/stakify/public/index.html
  Level1/staking-dapp/stakify/public/logo-192.png
  Level1/staking-dapp/stakify/public/manifest.json
  Level1/staking-dapp/stakify/public/robots.txt
  Level1/staking-dapp/stakify/src/App.css
  Level1/staking-dapp/stakify/src/App.jsx
  Level1/staking-dapp/stakify/src/artifacts/build-info/61cb045dff565a0d17a25a793423ce99.json
  Level1/staking-dapp/stakify/src/artifacts/contracts/Staking.sol/Staking.dbg.json
  Level1/staking-dapp/stakify/src/artifacts/contracts/Staking.sol/Staking.json
  Level1/staking-dapp/stakify/src/components/Navbar.jsx
  Level1/staking-dapp/stakify/src/components/StakeModal.jsx
  Level1/staking-dapp/stakify/src/images/polygon-matic-logo.svg
  Level1/staking-dapp/stakify/src/index.css
  Level1/staking-dapp/stakify/src/index.js
Labels: SSOC22, SSOC22-INTERMEDIATE

#44 Readme file add
  Level0/Login_Page/readme.md
  Level0/readme.md
Labels: SSOC22, SSOC22-BEGINNER

#62 NFT-MARKET-Place
  Level2/NFT-MARKET-PLACE/.gitignore
  Level2/NFT-MARKET-PLACE/Sample_Marketplace.json
  Level2/NFT-MARKET-PLACE/contracts/NFTMarketplace.sol
  Level2/NFT-MARKET-PLACE/hardhat.config.js
  Level2/NFT-MARKET-PLACE/package-lock.json
  Level2/NFT-MARKET-PLACE/package.json
  Level2/NFT-MARKET-PLACE/public/favicon.ico
  Level2/NFT-MARKET-PLACE/public/index.html
  Level2/NFT-MARKET-PLACE/public/logo192.png
  Level2/NFT-MARKET-PLACE/public/logo512.png
  Level2/NFT-MARKET-PLACE/public/manifest.json
  Level2/NFT-MARKET-PLACE/public/myfavicon.jpg
  Level2/NFT-MARKET-PLACE/public/robots.txt
  Level2/NFT-MARKET-PLACE/readme.md
  Level2/NFT-MARKET-PLACE/scripts/deploy.js
  Level2/NFT-MARKET-PLACE/scripts/testing.js
  Level2/NFT-MARKET-PLACE/src/App.css
  Level2/NFT-MARKET-PLACE/src/App.js
  Level2/NFT-MARKET-PLACE/src/App.test.js
  Level2/NFT-MARKET-PLACE/src/Marketplace.json
  Level2/NFT-MARKET-PLACE/src/add image.png
  Level2/NFT-MARKET-PLACE/src/axie-default.png
  Level2/NFT-MARKET-PLACE/src/bg.jpg
  Level2/NFT-MARKET-PLACE/src/bg.webp
  Level2/NFT-MARKET-PLACE/src/components/Marketplace.js
  Level2/NFT-MARKET-PLACE/src/components/NFTTile.js
  Level2/NFT-MARKET-PLACE/src/components/NFTpage.js
  Level2/NFT-MARKET-PLACE/src/components/Navbar.js
  Level2/NFT-MARKET-PLACE/src/components/Profile.js
  Level2/NFT-MARKET-PLACE/src/components/SellNFT.js
  Level2/NFT-MARKET-PLACE/src/full_logo.png
  Level2/NFT-MARKET-PLACE/src/image.png
  Level2/NFT-MARKET-PLACE/src/index.css
  Level2/NFT-MARKET-PLACE/src/index.js
  Level2/NFT-MARKET-PLACE/src/logo.svg
  Level2/NFT-MARKET-PLACE/src/logo_3.png
  Level2/NFT-MARKET-PLACE/src/myfavicon.jpg
  Level2/NFT-MARKET-PLACE/src/pinata.js
  Level2/NFT-MARKET-PLACE/src/reportWebVitals.js
  Level2/NFT-MARKET-PLACE/src/setupTests.js
  Level2/NFT-MARKET-PLACE/src/tile.jpeg
  Level2/NFT-MARKET-PLACE/test/sample-test.js
Labels: SSOC22, SSOC22-ADVANCED

#65 added files for Issue - #63
  Level1/todo-dapp/.gitignore
  Level1/todo-dapp/README.md
  Level1/todo-dapp/contracts/Manager.sol
  Level1/todo-dapp/hardhat.config.js
  Level1/todo-dapp/package-lock.json
  Level1/todo-dapp/package.json
  Level1/todo-dapp/public/favicon.ico
  Level1/todo-dapp/public/index.html
  Level1/todo-dapp/public/logo192.png
  Level1/todo-dapp/public/logo512.png
  Level1/todo-dapp/public/robots.txt
  Level1/todo-dapp/scripts/deploy.js
  Level1/todo-dapp/src/App.css
  Level1/todo-dapp/src/App.jsx
  Level1/todo-dapp/src/artifacts/build-info/463b0d9204866dfc73351bf8db7fb8be.json
  Level1/todo-dapp/src/artifacts/contracts/Manager.sol/Manager.dbg.json
  Level1/todo-dapp/src/artifacts/contracts/Manager.sol/Manager.json
  Level1/todo-dapp/src/index.css
  Level1/todo-dapp/src/index.js
  Level1/todo-dapp/src/secrets.json
  Level1/todo-dapp/test/manager-test.js
Labels: SSOC22, SSOC22-INTERMEDIATE

#64 A brief summary about this repo
  Summary.md
Labels: SSOC22, SSOC22-BEGINNER
