Repository Vikash-8090-Yadav/Future.WebNet, pull requests merged in 2023-07, with the labels that each got.

#387 [SSoC 2.0] Time Watcher Project Ready
  Frontend-Projects/Time-Watcher/README.md
  Frontend-Projects/Time-Watcher/index.html
  Frontend-Projects/Time-Watcher/logo.png
  Frontend-Projects/Time-Watcher/script.js
  Frontend-Projects/Time-Watcher/style.css
  Frontend-Projects/Time-Watcher/time-logo.png
Labels: Ready to Merge, SSOC

#379 Random Password Generator (#357)
  Frontend-Projects/Random Password Generator/Readme.md
  Frontend-Projects/Random Password Generator/index.html
  Frontend-Projects/Random Password Generator/script.js
  Frontend-Projects/Random Password Generator/style.css
Labels: Ready to Merge, SSOC

#323 [SSoC 2.0] Music Guess Game Done
  Frontend-Projects/Music Guess Game/README.md
  Frontend-Projects/Music Guess Game/images/Music_Guess_Game.png
  Frontend-Projects/Music Guess Game/images/Music_Guess_Game1.png
  Frontend-Projects/Music Guess Game/images/PlayingCaste.gif
  Frontend-Projects/Music Guess Game/index.html
  Frontend-Projects/Music Guess Game/script.js
  Frontend-Projects/Music Guess Game/songs/Aafat - Liger.mp3
  Frontend-Projects/Music Guess Game/songs/Apna Bna Le.mp3
  Frontend-Projects/Music Guess Game/songs/Chorbazari.mp3
  Frontend-Projects/Music Guess Game/songs/Chupke Chupke.mp3
  Frontend-Projects/Music Guess Game/songs/Current Laga Re.mp3
  Frontend-Projects/Music Guess Game/songs/Jhoome Jo Pathan.mp3
  Frontend-Projects/Music Guess Game/songs/Nacho Nacho.mp3
  Frontend-Projects/Music Guess Game/songs/O Saki Saki.mp3
  Frontend-Projects/Music Guess Game/songs/Thumkeswari.mp3
  Frontend-Projects/Music Guess Game/sounds/gameOver.mp3
  Frontend-Projects/Music Guess Game/sounds/playAgain.mp3
  Frontend-Projects/Music Guess Game/sounds/rightAnswer.mp3
  Frontend-Projects/Music Guess Game/sounds/wrongAnswer.mp3
  Frontend-Projects/Music Guess Game/style.css
Labels: Ready to Merge, SSOC

#325 BMI calculator
  Frontend-Projects/BMI Calculator/Images/healthy.jpg
  Frontend-Projects/BMI Calculator/Images/obese.jpg
  Frontend-Projects/BMI Calculator/Images/overweight.jpg
  Frontend-Projects/BMI Calculator/Images/underweight.jpg
  Frontend-Projects/BMI Calculator/Library _ Loom - 29 June 2023.mp4
  Frontend-Projects/BMI Calculator/Readme.md
  Frontend-Projects/BMI Calculator/image.png
  Frontend-Projects/BMI Calculator/index.html
  Frontend-Projects/BMI Calculator/script.js
  Frontend-Projects/BMI Calculator/style.css
Labels: Ready to Merge, SSOC

#394 [SSoC 2.0] Leap Year Project Completed
  Frontend-Projects/Leap_Years_In_A_Range/README.md
  Frontend-Projects/Leap_Years_In_A_Range/favicon.ico
  Frontend-Projects/Leap_Years_In_A_Range/index.html
  Frontend-Projects/Leap_Years_In_A_Range/script.js
  Frontend-Projects/Leap_Years_In_A_Range/style.css
Labels: Ready to Merge, SSOC

#402 [SSoC 2.0] Biography on Mahatma Gandhi Project
  Frontend-Projects/Mahatma_Gandhi_Biography/README.md
  Frontend-Projects/Mahatma_Gandhi_Biography/index.html
  Frontend-Projects/Mahatma_Gandhi_Biography/style.css
Labels: Ready to Merge, SSOC

#393 Task Manager web application
  Frontend-Projects/taskmanager/Readme.md
  Frontend-Projects/taskmanager/script.js
  Frontend-Projects/taskmanager/styles.css
  Frontend-Projects/taskmanager/task manager vdo.mp4
  Frontend-Projects/taskmanager/task manager.html
Labels: Ready to Merge, SSOC

#415 Magic Notes React app added issue #400
  Frontend-Projects/Magic_Notes/.gitignore
  Frontend-Projects/Magic_Notes/README.md
  Frontend-Projects/Magic_Notes/package-lock.json
  Frontend-Projects/Magic_Notes/package.json
  Frontend-Projects/Magic_Notes/public/index.html
  Frontend-Projects/Magic_Notes/public/style.css
  Frontend-Projects/Magic_Notes/src/components/App.jsx
  Frontend-Projects/Magic_Notes/src/components/CreateArea.jsx
  Frontend-Projects/Magic_Notes/src/components/Footer.jsx
  Frontend-Projects/Magic_Notes/src/components/Header.jsx
  Frontend-Projects/Magic_Notes/src/components/Note.jsx
  Frontend-Projects/Magic_Notes/src/index.js
Labels: Ready to Merge, SSOC

#424 [SSoC 2.0] ChatGPT Clone Ready
  Frontend-Projects/ChatGPT_Clone/README.md
  Frontend-Projects/ChatGPT_Clone/index.html
  Frontend-Projects/ChatGPT_Clone/index.js
  Frontend-Projects/ChatGPT_Clone/style.css
Labels: Ready to Merge, SSOC

#423 PWD Help
  Frontend-Projects/PWD Help/Readme.md
  Frontend-Projects/PWD Help/pwd help vdo (2).mp4
  Frontend-Projects/PWD Help/pwd ss.png
  Frontend-Projects/PWD Help/pwd.html
  Frontend-Projects/PWD Help/script.js
  Frontend-Projects/PWD Help/style.css
Labels: Ready to Merge, SSOC

#426 Super Burger Landpage issue no. #248
  Frontend-Projects/superburger/.gitignore
  Frontend-Projects/superburger/README.md
  Frontend-Projects/superburger/index.html
  Frontend-Projects/superburger/main.js
  Frontend-Projects/superburger/package-lock.json
  Frontend-Projects/superburger/package.json
  Frontend-Projects/superburger/public/4301493_burger_fast_fastfood_food_hamburger_icon-e1f1ef5c.svg
  Frontend-Projects/superburger/public/540f74001ca90a19263c66165621d597-06317efd.gif
  Frontend-Projects/superburger/public/BBQ_Dish-ae13f617.png
  Frontend-Projects/superburger/public/Burger_effect_1-86146610.png
  Frontend-Projects/superburger/public/Burger_month-68b72660.png
  Frontend-Projects/superburger/public/Gerald_G_Fast_Food_Lunch_Dinner_(FF_Menu)_6-391ed2eb.png
  Frontend-Projects/superburger/public/fresh_pizza-6814a75d.png
  Frontend-Projects/superburger/public/ribs-66a1fceb.png
  Frontend-Projects/superburger/public/smoke_burger-90a9df1f.png
  Frontend-Projects/superburger/public/smokey_bacon_1-a8bb0ddb.png
  Frontend-Projects/superburger/public/steak_1-b7e40c98.png
  Frontend-Projects/superburger/style.css
Labels: Changes Requested, Ready to Merge, SSOC

#436 Hotstar clone
  Frontend-Projects/Hotsar Clone/Index.html
  Frontend-Projects/Hotsar Clone/README.md
  Frontend-Projects/Hotsar Clone/images/images/add.png
  Frontend-Projects/Hotsar Clone/images/images/disney.PNG
  Frontend-Projects/Hotsar Clone/images/images/geographic.PNG
  Frontend-Projects/Hotsar Clone/images/images/logo.png
  Frontend-Projects/Hotsar Clone/images/images/marvel.PNG
  Frontend-Projects/Hotsar Clone/images/images/nxt.png
  Frontend-Projects/Hotsar Clone/images/images/pixar.PNG
  Frontend-Projects/Hotsar Clone/images/images/play.png
  Frontend-Projects/Hotsar Clone/images/images/poster 1.png
  Frontend-Projects/Hotsar Clone/images/images/poster 10.png
  Frontend-Projects/Hotsar Clone/images/images/poster 11.png
  Frontend-Projects/Hotsar Clone/images/images/poster 12.png
  Frontend-Projects/Hotsar Clone/images/images/poster 2.png
  Frontend-Projects/Hotsar Clone/images/images/poster 3.png
  Frontend-Projects/Hotsar Clone/images/images/poster 4.png
  Frontend-Projects/Hotsar Clone/images/images/poster 5.png
  Frontend-Projects/Hotsar Clone/images/images/poster 6.png
  Frontend-Projects/Hotsar Clone/images/images/poster 7.png
  Frontend-Projects/Hotsar Clone/images/images/poster 8.png
  Frontend-Projects/Hotsar Clone/images/images/poster 9.png
  Frontend-Projects/Hotsar Clone/images/images/pre.png
  Frontend-Projects/Hotsar Clone/images/images/slider 1.PNG
  Frontend-Projects/Hotsar Clone/images/images/slider 2.PNG
  Frontend-Projects/Hotsar Clone/images/images/slider 3.PNG
  Frontend-Projects/Hotsar Clone/images/images/slider 4.PNG
  Frontend-Projects/Hotsar Clone/images/images/slider 5.PNG
  Frontend-Projects/Hotsar Clone/images/images/star-wars.PNG
  Frontend-Projects/Hotsar Clone/index.js
  Frontend-Projects/Hotsar Clone/styles.css
  Frontend-Projects/Hotsar Clone/videos/videos/disney.mp4
  Frontend-Projects/Hotsar Clone/videos/videos/geographic.mp4
  Frontend-Projects/Hotsar Clone/videos/videos/marvel.mp4
  Frontend-Projects/Hotsar Clone/videos/videos/pixar.mp4
  Frontend-Projects/Hotsar Clone/videos/videos/star-war.mp4
Labels: Ready to Merge, SSOC

#417 Talent Portal
  Frontend-Projects/Talent Portal/README.md
  Frontend-Projects/Talent Portal/image.png
  Frontend-Projects/Talent Portal/index.html
  Frontend-Projects/Talent Portal/style.css
Labels: SSOC

#437 Image Slider #359
  Frontend-Projects/ImageSlider/README.md
  Frontend-Projects/ImageSlider/index.html
  Frontend-Projects/ImageSlider/script.js
  Frontend-Projects/ImageSlider/style.css
Labels: Ready to Merge, SSOC

#442 Stopwatch
  Frontend-Projects/Stopwatch/README.md
  Frontend-Projects/Stopwatch/index.html
  Frontend-Projects/Stopwatch/script.js
  Frontend-Projects/Stopwatch/style.css
Labels: Ready to Merge, SSOC

#443 [SSoC 2.0] Large Factorial Calculator Ready
  Frontend-Projects/Large_Factorial_Calculator/README.md
  Frontend-Projects/Large_Factorial_Calculator/index.html
  Frontend-Projects/Large_Factorial_Calculator/script.js
  Frontend-Projects/Large_Factorial_Calculator/style.css
Labels: Ready to Merge, SSOC

#450 [SSoC 2.0] FAQ Template Website Ready
  Frontend-Projects/FAQ_Accordion/README.md
  Frontend-Projects/FAQ_Accordion/index.html
  Frontend-Projects/FAQ_Accordion/script.js
  Frontend-Projects/FAQ_Accordion/style.css
Labels: Ready to Merge, SSOC

#451 [SSoC 2.0] Music Studio Game Completed
  Frontend-Projects/Music_Studio_Game/README.md
  Frontend-Projects/Music_Studio_Game/app.js
  Frontend-Projects/Music_Studio_Game/images/clap.png
  Frontend-Projects/Music_Studio_Game/images/closed-hihat.png
  Frontend-Projects/Music_Studio_Game/images/crash.png
  Frontend-Projects/Music_Studio_Game/images/kick.png
  Frontend-Projects/Music_Studio_Game/images/open-hihat.png
  Frontend-Projects/Music_Studio_Game/images/snare.png
  Frontend-Projects/Music_Studio_Game/index.html
  Frontend-Projects/Music_Studio_Game/sounds/sound1.mp3
  Frontend-Projects/Music_Studio_Game/sounds/sound2.mp3
  Frontend-Projects/Music_Studio_Game/sounds/sound3.mp3
  Frontend-Projects/Music_Studio_Game/sounds/sound4.mp3
  Frontend-Projects/Music_Studio_Game/sounds/sound5.mp3
  Frontend-Projects/Music_Studio_Game/sounds/sound6.mp3
  Frontend-Projects/Music_Studio_Game/style.css
Labels: Ready to Merge, SSOC

#462 #355 Digital Clock
  Frontend-Projects/Digital Clock/README.md
  Frontend-Projects/Digital Clock/index.html
  Frontend-Projects/Digital Clock/script.js
  Frontend-Projects/Digital Clock/style.css
Labels: Ready to Merge, SSOC

#455 Added one more project
  Project_Ideas/README.md
Labels: Ready to Merge, SSOC

#456 Unit converter
  Frontend-Projects/Unit converter/README.md
  Frontend-Projects/Unit converter/Unit Converter.png
  Frontend-Projects/Unit converter/index.html
  Frontend-Projects/Unit converter/index.js
  Frontend-Projects/Unit converter/style.css
Labels: Ready to Merge, SSOC

#471 [SSoC 2.0] Neon Light Effect using CSS
  Frontend-Projects/Neon-Light/README.md
  Frontend-Projects/Neon-Light/index.html
  Frontend-Projects/Neon-Light/style.css
Labels: Ready to Merge, SSOC

#338 netflix Added
  Frontend-Projects/Netflix_Landing_Page/.gitignore
  Frontend-Projects/Netflix_Landing_Page/README.md
  Frontend-Projects/Netflix_Landing_Page/Web capture_1-7-2023_154039_localhost.jpeg
  Frontend-Projects/Netflix_Landing_Page/Web capture_1-7-2023_154117_localhost.jpeg
  Frontend-Projects/Netflix_Landing_Page/image.png
  Frontend-Projects/Netflix_Landing_Page/package-lock.json
  Frontend-Projects/Netflix_Landing_Page/package.json
  Frontend-Projects/Netflix_Landing_Page/public/favicon.ico
  Frontend-Projects/Netflix_Landing_Page/public/index.html
  Frontend-Projects/Netflix_Landing_Page/public/logo192.png
  Frontend-Projects/Netflix_Landing_Page/public/logo512.png
  Frontend-Projects/Netflix_Landing_Page/public/manifest.json
  Frontend-Projects/Netflix_Landing_Page/public/robots.txt
  Frontend-Projects/Netflix_Landing_Page/src/App.js
  Frontend-Projects/Netflix_Landing_Page/src/App.scss
  Frontend-Projects/Netflix_Landing_Page/src/Components/Header/Header.jsx
  Frontend-Projects/Netflix_Landing_Page/src/Components/Home/CardImage.jsx
  Frontend-Projects/Netflix_Landing_Page/src/Components/Home/Home.jsx
  Frontend-Projects/Netflix_Landing_Page/src/Components/Home/Home.scss
  Frontend-Projects/Netflix_Landing_Page/src/Components/Home/Row.jsx
  Frontend-Projects/Netflix_Landing_Page/src/images/Cardimg.png
  Frontend-Projects/Netflix_Landing_Page/src/images/logo.png
  Frontend-Projects/Netflix_Landing_Page/src/index.js
Labels: Ready to Merge, SSOC

#480 Netflix clone
  Frontend-Projects/netflix_clone/Readme.md
  Frontend-Projects/netflix_clone/background.jpg
  Frontend-Projects/netflix_clone/index.html
  Frontend-Projects/netflix_clone/logo.png
  Frontend-Projects/netflix_clone/main.js
  Frontend-Projects/netflix_clone/style.css
  Frontend-Projects/netflix_clone/tab-content-1.png
  Frontend-Projects/netflix_clone/tab-content-2-1.png
  Frontend-Projects/netflix_clone/tab-content-2-2.png
  Frontend-Projects/netflix_clone/tab-content-2-3.png
Labels: Ready to Merge, SSOC

#483 [SSoC 2.0] Recipe Finder Website Completed
  Frontend-Projects/Recipe-Finder-Website/README.md
  Frontend-Projects/Recipe-Finder-Website/index.html
  Frontend-Projects/Recipe-Finder-Website/script.js
  Frontend-Projects/Recipe-Finder-Website/style.css
Labels: Ready to Merge, SSOC

#476 [SSoC 2.0] Gym Website Completed
  Frontend-Projects/MyGym-Website/README.md
  Frontend-Projects/MyGym-Website/css/aos.css
  Frontend-Projects/MyGym-Website/css/bootstrap.min.css
  Frontend-Projects/MyGym-Website/css/main.css
  Frontend-Projects/MyGym-Website/images/class/cardio-class.jpg
  Frontend-Projects/MyGym-Website/images/class/crossfit-class.jpg
  Frontend-Projects/MyGym-Website/images/class/yoga-class.jpg
  Frontend-Projects/MyGym-Website/images/hero-bg.jpg
  Frontend-Projects/MyGym-Website/images/team/undraw_energizer_2224.svg
  Frontend-Projects/MyGym-Website/images/team/undraw_yoga_248n.svg
  Frontend-Projects/MyGym-Website/index.html
  Frontend-Projects/MyGym-Website/js/aos.js
  Frontend-Projects/MyGym-Website/js/bootstrap.min.js
  Frontend-Projects/MyGym-Website/js/script.js
  Frontend-Projects/MyGym-Website/js/smoothscroll.js
Labels: Ready to Merge, SSOC

#495 Genderguess
  Frontend-Projects/Guess The Gender By Name/README.md
  Frontend-Projects/Guess The Gender By Name/index.html
  Frontend-Projects/Guess The Gender By Name/style.css
Labels: Ready to Merge, SSOC

#482 Update in Cricket Play
  Frontend-Projects/cricket/Champions.jpg
  Frontend-Projects/cricket/README.md
  Frontend-Projects/cricket/Records.html
  Frontend-Projects/cricket/champs.html
  Frontend-Projects/cricket/cricket records.jpg
  Frontend-Projects/cricket/header.css
  Frontend-Projects/cricket/images/cricket.png.jpg
  Frontend-Projects/cricket/images/image1.webp
  Frontend-Projects/cricket/images/image2.webp
  Frontend-Projects/cricket/images/image3.webp
  Frontend-Projects/cricket/images/image4.webp
  Frontend-Projects/cricket/images/image5.webp
  Frontend-Projects/cricket/images/image6.webp
  Frontend-Projects/cricket/images/video.gif
  Frontend-Projects/cricket/index.html
  Frontend-Projects/cricket/screenshot.png
  Frontend-Projects/cricket/screenshot1.png
  Frontend-Projects/cricket/styles.css
Labels: Ready to Merge, SSOC

#499 To do task
  Level1/Check-it/.cache/files/__replit_disk_meta.json
  Level1/Check-it/.cache/files/modules.stamp
  Level1/Check-it/.cache/files/nix/env.json
  Level1/Check-it/.cache/replit/__replit_disk_meta.json
  Level1/Check-it/.cache/replit/modules.stamp
  Level1/Check-it/.cache/replit/nix/env.json
  Level1/Check-it/.upm/store.json
  Level1/Check-it/README.md
  Level1/Check-it/backend/build/contracts/TaskContract.json
  Level1/Check-it/backend/contracts/.gitkeep
  Level1/Check-it/backend/contracts/TaskContract.sol
  Level1/Check-it/backend/migrations/.gitkeep
  Level1/Check-it/backend/migrations/1_initial_migration.js
  Level1/Check-it/backend/test/.gitkeep
  Level1/Check-it/backend/truffle-config.js
  Level1/Check-it/client/.eslintrc.json
  Level1/Check-it/client/.gitignore
  Level1/Check-it/client/README.md
  Level1/Check-it/client/components/ConnectWalletButton.js
  Level1/Check-it/client/components/Navbar.js
  Level1/Check-it/client/components/Task.js
  Level1/Check-it/client/components/TodoList.js
  Level1/Check-it/client/components/WrongNetworkMessage.js
  Level1/Check-it/client/config.js
  Level1/Check-it/client/next.config.js
  Level1/Check-it/client/package-lock.json
  Level1/Check-it/client/package.json
  Level1/Check-it/client/pages/_app.js
  Level1/Check-it/client/pages/api/hello.js
  Level1/Check-it/client/pages/index.js
  Level1/Check-it/client/postcss.config.js
  Level1/Check-it/client/public/favicon.ico
  Level1/Check-it/client/public/vercel.svg
  Level1/Check-it/client/styles/Home.module.css
  Level1/Check-it/client/styles/globals.css
  Level1/Check-it/client/tailwind.config.js
  Level1/Check-it/client/yarn.lock
  Level1/Check-it/package-lock.json
  Level1/Check-it/package.json
Labels: Ready to Merge, SSOC

#384 Added Bookcase project
  Frontend-Projects/Bookcase/README.md
  Frontend-Projects/Bookcase/assets/bgImage.png
  Frontend-Projects/Bookcase/assets/book.png
  Frontend-Projects/Bookcase/assets/bookbg.jpg
  Frontend-Projects/Bookcase/assets/check-outline.svg
  Frontend-Projects/Bookcase/assets/check-solid.svg
  Frontend-Projects/Bookcase/assets/searchimg.png
  Frontend-Projects/Bookcase/assets/trash-fill.svg
  Frontend-Projects/Bookcase/assets/trash-outline.svg
  Frontend-Projects/Bookcase/assets/undo-ouline.svg
  Frontend-Projects/Bookcase/index.html
  Frontend-Projects/Bookcase/script.js
  Frontend-Projects/Bookcase/style.css
Labels: Ready to Merge, SSOC

#445 Lucky Die game Added
  Frontend-Projects/Lucky Die/PIG.css
  Frontend-Projects/Lucky Die/PIG.js
  Frontend-Projects/Lucky Die/README.md
  Frontend-Projects/Lucky Die/Untitled Diagram.drawio
  Frontend-Projects/Lucky Die/assets/Frame 1.png
  Frontend-Projects/Lucky Die/assets/Frame 2.png
  Frontend-Projects/Lucky Die/assets/Frame 3.png
  Frontend-Projects/Lucky Die/assets/Frame 4.png
  Frontend-Projects/Lucky Die/assets/Frame 5.png
  Frontend-Projects/Lucky Die/assets/Frame 6.png
  Frontend-Projects/Lucky Die/assets/Frame 8.png
  Frontend-Projects/Lucky Die/assets/Library _ Loom - 3 July 2023.mp4
  Frontend-Projects/Lucky Die/assets/img.jpg
  Frontend-Projects/Lucky Die/index.html
Labels: Ready to Merge, SSOC

#409 Added Ping Pong Multiplayer game
  Frontend-Projects/Ping_Pong Multiplayer/Library _ Loom - 3 July 2023.mp4
  Frontend-Projects/Ping_Pong Multiplayer/README.md
  Frontend-Projects/Ping_Pong Multiplayer/Screenshot (188).png
  Frontend-Projects/Ping_Pong Multiplayer/index.html
  Frontend-Projects/Ping_Pong Multiplayer/script.js
  Frontend-Projects/Ping_Pong Multiplayer/styles.css
Labels: Ready to Merge, SSOC

#477 Bucket_List is added
  Frontend-Projects/BucketList_Project/README.md
  Frontend-Projects/BucketList_Project/index.html
  Frontend-Projects/BucketList_Project/resources/css/img/adventure.jpg
  Frontend-Projects/BucketList_Project/resources/css/img/bgimage.webp
  Frontend-Projects/BucketList_Project/resources/css/img/headerpic.jpg
  Frontend-Projects/BucketList_Project/resources/css/img/headerpic2.jpg
  Frontend-Projects/BucketList_Project/resources/css/img/testimonial_bg.jpeg
  Frontend-Projects/BucketList_Project/resources/css/img/travelling.jpg
  Frontend-Projects/BucketList_Project/resources/css/style.css
  Frontend-Projects/BucketList_Project/resources/img/adventure.jpg
  Frontend-Projects/BucketList_Project/resources/img/backwater.webp
  Frontend-Projects/BucketList_Project/resources/img/bucket.png
  Frontend-Projects/BucketList_Project/resources/img/bucket2.png
  Frontend-Projects/BucketList_Project/resources/img/bucket3.png
  Frontend-Projects/BucketList_Project/resources/img/bungee.jpeg
  Frontend-Projects/BucketList_Project/resources/img/camping-small.jpg
  Frontend-Projects/BucketList_Project/resources/img/camping.jpg
  Frontend-Projects/BucketList_Project/resources/img/kerala.webp
  Frontend-Projects/BucketList_Project/resources/img/ladakh.webp
  Frontend-Projects/BucketList_Project/resources/img/rafting.jpg
  Frontend-Projects/BucketList_Project/resources/img/sikkim.webp
  Frontend-Projects/BucketList_Project/resources/img/testimg1.jpg!d
  Frontend-Projects/BucketList_Project/resources/img/testimg2.jpeg
  Frontend-Projects/BucketList_Project/resources/img/testimg3.jpeg
  Frontend-Projects/BucketList_Project/resources/img/travelling.jpg
  Frontend-Projects/BucketList_Project/resources/img/trekking.jpeg
  Frontend-Projects/BucketList_Project/resources/img/vrindavan.webp
  Frontend-Projects/BucketList_Project/resources/img/zipilinning.jpg
  Frontend-Projects/BucketList_Project/resources/sass/_base.scss
  Frontend-Projects/BucketList_Project/resources/sass/_component.scss
  Frontend-Projects/BucketList_Project/resources/sass/_layout.scss
  Frontend-Projects/BucketList_Project/resources/sass/main.scss
  Frontend-Projects/BucketList_Project/vendors/favicon/favicon-16x16.png
  Frontend-Projects/BucketList_Project/vendors/favicon/favicon-180x180-2.png
  Frontend-Projects/BucketList_Project/vendors/favicon/favicon-180x180.png
  Frontend-Projects/BucketList_Project/vendors/favicon/favicon-32x32.png
  Frontend-Projects/BucketList_Project/vendors/fonts/fonts/linea-basic-10.eot
  Frontend-Projects/BucketList_Project/vendors/fonts/fonts/linea-basic-10.svg
  Frontend-Projects/BucketList_Project/vendors/fonts/fonts/linea-basic-10.ttf
  Frontend-Projects/BucketList_Project/vendors/fonts/fonts/linea-basic-10.woff
  Frontend-Projects/BucketList_Project/vendors/fonts/icon_styles.css
  Frontend-Projects/BucketList_Project/vendors/fonts/icons-reference.html
Labels: Ready to Merge, SSOC
