Repository Vikash-8090-Yadav/Future.WebNet, pull requests merged in 2023-06, with the labels that each got.

#246 Google Clone
  Frontend-Projects/Google Clone/Advanced.html
  Frontend-Projects/Google Clone/Images.html
  Frontend-Projects/Google Clone/Readme.md
  Frontend-Projects/Google Clone/google.png
  Frontend-Projects/Google Clone/googleimage.png
  Frontend-Projects/Google Clone/index.html
  Frontend-Projects/Google Clone/style.css
Labels: SSOC

#276 Improve the UI and functionality of SendToEther Project of Level0
  Level0/SendToEther/bg.jpg
  Level0/SendToEther/index.css
  Level0/SendToEther/index.html
  Level0/SendToEther/index.js
  Level0/SendToEther/success.css
  Level0/SendToEther/success.html
  Level0/readme.md
Labels: SSOC

#253 updated hover buttons
  Level0/Voting/index.css
Labels: SSOC

#273 docs: add close old issues workflow
  .github/workflows/close_old_issues.yml
Labels: SSOC

#303 created weather app
  Frontend-Projects/WeatherApp/README.md
  Frontend-Projects/WeatherApp/index.html
  Frontend-Projects/WeatherApp/script.js
  Frontend-Projects/WeatherApp/style.css
  Frontend-Projects/Zomato-Clone/README.md
  Frontend-Projects/Zomato-Clone/index.html
  Frontend-Projects/Zomato-Clone/style.css
Labels: SSOC

#304 New Frontend Project: Drum Game #286
  Frontend-Projects/Drum Player/README.md
  Frontend-Projects/Drum Player/images/cover1.jpg
  Frontend-Projects/Drum Player/images/crash.png
  Frontend-Projects/Drum Player/images/kick.png
  Frontend-Projects/Drum Player/images/snare.png
  Frontend-Projects/Drum Player/images/tom1.png
  Frontend-Projects/Drum Player/images/tom2.png
  Frontend-Projects/Drum Player/images/tom3.png
  Frontend-Projects/Drum Player/images/tom4.png
  Frontend-Projects/Drum Player/index.html
  Frontend-Projects/Drum Player/index.js
  Frontend-Projects/Drum Player/sounds/crash.mp3
  Frontend-Projects/Drum Player/sounds/kick-bass.mp3
  Frontend-Projects/Drum Player/sounds/snare.mp3
  Frontend-Projects/Drum Player/sounds/tom-1.mp3
  Frontend-Projects/Drum Player/sounds/tom-2.mp3
  Frontend-Projects/Drum Player/sounds/tom-3.mp3
  Frontend-Projects/Drum Player/sounds/tom-4.mp3
  Frontend-Projects/Drum Player/styles.css
Labels: SSOC

#312 RockPaperScissor Game under SSOC
  Frontend-Projects/RockPaperScissors/README.md
  Frontend-Projects/RockPaperScissors/buttons/buttons.css
  Frontend-Projects/RockPaperScissors/general/general.css
  Frontend-Projects/RockPaperScissors/images/background.avif
  Frontend-Projects/RockPaperScissors/images/paper.png
  Frontend-Projects/RockPaperScissors/images/rock.png
  Frontend-Projects/RockPaperScissors/images/scissors.png
  Frontend-Projects/RockPaperScissors/index.html
Labels: SSOC

#329 changed some lines in README.md
  README.md
Labels: documentation, SSOC

#311 Added Youtube-Clone Project
  Frontend-Projects/Youtube-clone/Channel Pictures/t1.webp
  Frontend-Projects/Youtube-clone/Channel Pictures/t10.jpeg
  Frontend-Projects/Youtube-clone/Channel Pictures/t11.webp
  Frontend-Projects/Youtube-clone/Channel Pictures/t12.jpeg
  Frontend-Projects/Youtube-clone/Channel Pictures/t2.webp
  Frontend-Projects/Youtube-clone/Channel Pictures/t3.jpeg
  Frontend-Projects/Youtube-clone/Channel Pictures/t4.jpeg
  Frontend-Projects/Youtube-clone/Channel Pictures/t5.webp
  Frontend-Projects/Youtube-clone/Channel Pictures/t6.jpeg
  Frontend-Projects/Youtube-clone/Channel Pictures/t7.webp
  Frontend-Projects/Youtube-clone/Channel Pictures/t8.jpeg
  Frontend-Projects/Youtube-clone/Channel Pictures/t9.webp
  Frontend-Projects/Youtube-clone/README.md
  Frontend-Projects/Youtube-clone/Thumbnails/1.webp
  Frontend-Projects/Youtube-clone/Thumbnails/10.jpeg
  Frontend-Projects/Youtube-clone/Thumbnails/11.webp
  Frontend-Projects/Youtube-clone/Thumbnails/12.jpeg
  Frontend-Projects/Youtube-clone/Thumbnails/2.jpeg
  Frontend-Projects/Youtube-clone/Thumbnails/3.webp
  Frontend-Projects/Youtube-clone/Thumbnails/4.jpeg
  Frontend-Projects/Youtube-clone/Thumbnails/5.webp
  Frontend-Projects/Youtube-clone/Thumbnails/6.jpeg
  Frontend-Projects/Youtube-clone/Thumbnails/7.webp
  Frontend-Projects/Youtube-clone/Thumbnails/8.jpeg
  Frontend-Projects/Youtube-clone/Thumbnails/9.webp
  Frontend-Projects/Youtube-clone/Youtube.html
  Frontend-Projects/Youtube-clone/icons/explore.svg
  Frontend-Projects/Youtube-clone/icons/hamburger-menu.svg
  Frontend-Projects/Youtube-clone/icons/home.svg
  Frontend-Projects/Youtube-clone/icons/library.svg
  Frontend-Projects/Youtube-clone/icons/my-channel.jpg
  Frontend-Projects/Youtube-clone/icons/notifications.svg
  Frontend-Projects/Youtube-clone/icons/originals.svg
  Frontend-Projects/Youtube-clone/icons/search.svg
  Frontend-Projects/Youtube-clone/icons/subscriptions.svg
  Frontend-Projects/Youtube-clone/icons/upload.svg
  Frontend-Projects/Youtube-clone/icons/voice-search-icon.svg
  Frontend-Projects/Youtube-clone/icons/youtube-apps.svg
  Frontend-Projects/Youtube-clone/icons/youtube-logo.svg
  Frontend-Projects/Youtube-clone/icons/youtube-music.svg
  Frontend-Projects/Youtube-clone/styles/general.css
  Frontend-Projects/Youtube-clone/styles/header.css
  Frontend-Projects/Youtube-clone/styles/sidebar.css
  Frontend-Projects/Youtube-clone/styles/video.css
Labels: SSOC

#353 [SSoC 2.0] Solar System Project Completed
  Frontend-Projects/Solar System Model/README.md
  Frontend-Projects/Solar System Model/Screenshot.png
  Frontend-Projects/Solar System Model/favicon.ico
  Frontend-Projects/Solar System Model/index.html
  Frontend-Projects/Solar System Model/script.js
  Frontend-Projects/Solar System Model/style.css
Labels: SSOC

#332 Updated Codeclub project
  Frontend-Projects/Codeclub/.gitignore
  Frontend-Projects/Codeclub/README.md
  Frontend-Projects/Codeclub/about.html
  Frontend-Projects/Codeclub/index.html
  Frontend-Projects/Codeclub/members.html
  Frontend-Projects/Codeclub/package-lock.json
  Frontend-Projects/Codeclub/package.json
  Frontend-Projects/Codeclub/password.html
  Frontend-Projects/Codeclub/password.js
  Frontend-Projects/Codeclub/public/favicon.ico
  Frontend-Projects/Codeclub/public/index.html
  Frontend-Projects/Codeclub/public/logo192.png
  Frontend-Projects/Codeclub/public/logo512.png
  Frontend-Projects/Codeclub/public/manifest.json
  Frontend-Projects/Codeclub/public/robots.txt
  Frontend-Projects/Codeclub/src/App.css
  Frontend-Projects/Codeclub/src/App.js
  Frontend-Projects/Codeclub/src/App.test.js
  Frontend-Projects/Codeclub/src/components/About.jsx
  Frontend-Projects/Codeclub/src/components/Blogs.jsx
  Frontend-Projects/Codeclub/src/components/Contact.jsx
  Frontend-Projects/Codeclub/src/components/Home.jsx
  Frontend-Projects/Codeclub/src/components/ImageUploader.jsx
  Frontend-Projects/Codeclub/src/components/Navbar.jsx
  Frontend-Projects/Codeclub/src/components/Resources.jsx
  Frontend-Projects/Codeclub/src/components/about.css
  Frontend-Projects/Codeclub/src/components/blogs.css
  Frontend-Projects/Codeclub/src/components/contact.css
  Frontend-Projects/Codeclub/src/components/home.css
  Frontend-Projects/Codeclub/src/components/navbar.css
  Frontend-Projects/Codeclub/src/components/resources.css
  Frontend-Projects/Codeclub/src/img/backend.jpg
  Frontend-Projects/Codeclub/src/img/blog-icon.png
  Frontend-Projects/Codeclub/src/img/boy.png
  Frontend-Projects/Codeclub/src/img/community.png
  Frontend-Projects/Codeclub/src/img/dbms.png
  Frontend-Projects/Codeclub/src/img/dsa.jpg
  Frontend-Projects/Codeclub/src/img/equal.png
  Frontend-Projects/Codeclub/src/img/front.jpg
  Frontend-Projects/Codeclub/src/img/full stack.png
  Frontend-Projects/Codeclub/src/img/home.jpg
  Frontend-Projects/Codeclub/src/img/insta.png
  Frontend-Projects/Codeclub/src/img/linkedin.png
  Frontend-Projects/Codeclub/src/img/logo.png
  Frontend-Projects/Codeclub/src/img/m1.jpg
  Frontend-Projects/Codeclub/src/img/m2.jpg
  Frontend-Projects/Codeclub/src/img/mern.jpg
  Frontend-Projects/Codeclub/src/img/mern.png
  Frontend-Projects/Codeclub/src/img/plus.png
  Frontend-Projects/Codeclub/src/img/resources.png
  Frontend-Projects/Codeclub/src/img/twitter.png
  Frontend-Projects/Codeclub/src/index.css
  Frontend-Projects/Codeclub/src/index.js
  Frontend-Projects/Codeclub/src/logo.svg
  Frontend-Projects/Codeclub/src/reportWebVitals.js
  Frontend-Projects/Codeclub/src/setupTests.js
  Frontend-Projects/Codeclub/styles.css
Labels: SSOC

#374 Issue 371
  Blog/Blockchain & Web3/BlockchainAndWeb3.md
  Blog/Blockchain & Web3/blockchain.jpg
Labels: Ready to Merge, SSOC

#377 [SSoC 2.0] Guess Gender By Name Project Ready
  Frontend-Projects/Guess The Gender By Name/README.md
  Frontend-Projects/Guess The Gender By Name/female.svg
  Frontend-Projects/Guess The Gender By Name/index.html
  Frontend-Projects/Guess The Gender By Name/logo.svg
  Frontend-Projects/Guess The Gender By Name/male.svg
  Frontend-Projects/Guess The Gender By Name/script.js
  Frontend-Projects/Guess The Gender By Name/style.css
Labels: Ready to Merge, SSOC

#378 Month Calender
  Frontend-Projects/Month Calender/Readme.md
  Frontend-Projects/Month Calender/index.html
  Frontend-Projects/Month Calender/script.js
  Frontend-Projects/Month Calender/style.css
Labels: Ready to Merge, SSOC
